// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Result of prime generation: a list of primes.
 */
export class VaeaPrimeList {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Generates `count` NTT-friendly 28-bit primes for polynomial size `n`.
     */
    static generate(n: number, count: number): VaeaPrimeList;

    /**
     * Returns the number of primes in the list.
     */
    len(): number;

    /**
     * Returns the prime at the given index (0-based).
     */
    get(index: number): number;
}