// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const VaeaPrimeList_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.VaeaPrimeList_destroy(ptr);
});

/**
 * Result of prime generation: a list of primes.
 */
export class VaeaPrimeList {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("VaeaPrimeList is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            VaeaPrimeList_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Generates `count` NTT-friendly 28-bit primes for polynomial size `n`.
     */
    static generate(n, count) {

        const result = wasm.VaeaPrimeList_generate(n, count);

        try {
            return new VaeaPrimeList(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Returns the number of primes in the list.
     */
    len() {

        const result = wasm.VaeaPrimeList_len(this.ffiValue);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Returns the prime at the given index (0-based).
     */
    get(index) {

        const result = wasm.VaeaPrimeList_get(this.ffiValue, index);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}