// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * Error codes returned by VaeaNTT operations.
 */
export class VaeaNttError {
    #value = undefined;

    static #values = new Map([
        ["InvalidSize", 0],
        ["NotPrime", 1],
        ["NotNttFriendly", 2],
        ["PrimeTooLarge", 3],
        ["InvalidBufferLength", 4]
    ]);

    static getAllEntries() {
        return VaeaNttError.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return VaeaNttError.#objectValues[arguments[1]];
        }

        if (value instanceof VaeaNttError) {
            return value;
        }

        let intVal = VaeaNttError.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return VaeaNttError.#objectValues[intVal];
        }

        throw TypeError(value + " is not a VaeaNttError and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new VaeaNttError(value);
    }

    get value(){
        return [...VaeaNttError.#values.keys()][this.#value];
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = [
        new VaeaNttError(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new VaeaNttError(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        new VaeaNttError(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
        new VaeaNttError(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 3),
        new VaeaNttError(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 4),
    ];

    /**
     * N must be a power of 2 >= 2.
     */
    static InvalidSize = VaeaNttError.#objectValues[0];
    /**
     * q must be prime.
     */
    static NotPrime = VaeaNttError.#objectValues[1];
    /**
     * q must satisfy q ≡ 1 (mod 2N).
     */
    static NotNttFriendly = VaeaNttError.#objectValues[2];
    /**
     * q must be < 2^28.
     */
    static PrimeTooLarge = VaeaNttError.#objectValues[3];
    /**
     * Buffer length does not match the context's N.
     */
    static InvalidBufferLength = VaeaNttError.#objectValues[4];


    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}