// generated by diplomat-tool
import { VaeaNttError } from "./VaeaNttError.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const VaeaNtt32_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.VaeaNtt32_destroy(ptr);
});

/**
 * Opaque handle to a pre-computed NTT context for 28-bit primes.
 *
 * Create with `VaeaNtt32::try_new()`, then call `forward()`, `inverse()`,
 * or `negacyclic_mul()` on polynomial buffers.
 */
export class VaeaNtt32 {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("VaeaNtt32 is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            VaeaNtt32_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    /**
     * Creates a new NTT context.
     *
     * # Arguments
     * - `n` — polynomial size, must be a power of 2 ≥ 2
     * - `q` — prime < 2^28, must satisfy q ≡ 1 (mod 2N)
     *
     * Returns an error if parameters are invalid.
     */
    static tryNew(n, q) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.VaeaNtt32_try_new(diplomatReceive.buffer, n, q);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new VaeaNttError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('VaeaNttError.' + cause.value, { cause });
            }
            return new VaeaNtt32(diplomatRuntime.internalConstructor, diplomatRuntime.ptrRead(wasm, diplomatReceive.buffer), []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * Returns the polynomial size N.
     */
    getN() {

        const result = wasm.VaeaNtt32_get_n(this.ffiValue);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Returns the prime modulus q.
     */
    getQ() {

        const result = wasm.VaeaNtt32_get_q(this.ffiValue);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Forward NTT transform (in-place).
     *
     * `data` must have exactly N elements. All elements must be < q.
     */
    forward(data) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const dataSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, data, "u32")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.VaeaNtt32_forward(diplomatReceive.buffer, this.ffiValue, dataSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new VaeaNttError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('VaeaNttError.' + cause.value, { cause });
            }
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Inverse NTT transform (in-place, with N⁻¹ normalization).
     *
     * `data` must have exactly N elements.
     */
    inverse(data) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const dataSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, data, "u32")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.VaeaNtt32_inverse(diplomatReceive.buffer, this.ffiValue, dataSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new VaeaNttError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('VaeaNttError.' + cause.value, { cause });
            }
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Inverse NTT without N⁻¹ normalization (matches concrete-ntt behavior).
     *
     * `data` must have exactly N elements.
     */
    inverseLazy(data) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const dataSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, data, "u32")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.VaeaNtt32_inverse_lazy(diplomatReceive.buffer, this.ffiValue, dataSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new VaeaNttError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('VaeaNttError.' + cause.value, { cause });
            }
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Negacyclic polynomial multiplication in Z_q[X]/(X^N + 1).
     *
     * Computes `result = a × b mod (X^N + 1)` using NTT.
     * All three buffers must have exactly N elements.
     * `a` and `b` are modified (transformed to NTT domain).
     */
    negacyclicMul(a, b, result) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const aSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, a, "u32")));
        const bSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, b, "u32")));
        const resultSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, result, "u32")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.VaeaNtt32_negacyclic_mul(diplomatReceive.buffer, this.ffiValue, aSlice.ptr, bSlice.ptr, resultSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new VaeaNttError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('VaeaNttError.' + cause.value, { cause });
            }
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    /**
     * Pointwise multiplication of two NTT-domain polynomials.
     *
     * All three buffers must have exactly N elements.
     * Inputs must already be in NTT domain.
     */
    pointwiseMul(a, b, result) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const aSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, a, "u32")));
        const bSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, b, "u32")));
        const resultSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.slice(wasm, result, "u32")));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.VaeaNtt32_pointwise_mul(diplomatReceive.buffer, this.ffiValue, aSlice.ptr, bSlice.ptr, resultSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                const cause = new VaeaNttError(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
                throw new globalThis.Error('VaeaNttError.' + cause.value, { cause });
            }
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}