// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Error codes returned by VaeaNTT operations.
 */
export class VaeaNttError {

    /** @internal */
    static fromValue(value: VaeaNttError | string): VaeaNttError;

    get value(): string;

    /** @internal */
    get ffiValue(): number;

    /**
     * N must be a power of 2 >= 2.
     */
    static InvalidSize : VaeaNttError;
    /**
     * q must be prime.
     */
    static NotPrime : VaeaNttError;
    /**
     * q must satisfy q ≡ 1 (mod 2N).
     */
    static NotNttFriendly : VaeaNttError;
    /**
     * q must be < 2^28.
     */
    static PrimeTooLarge : VaeaNttError;
    /**
     * Buffer length does not match the context's N.
     */
    static InvalidBufferLength : VaeaNttError;


    constructor(value: VaeaNttError | string );
}