// generated by diplomat-tool
import type { VaeaNttError } from "./VaeaNttError"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * Opaque handle to a pre-computed NTT context for 28-bit primes.
 *
 * Create with `VaeaNtt32::try_new()`, then call `forward()`, `inverse()`,
 * or `negacyclic_mul()` on polynomial buffers.
 */
export class VaeaNtt32 {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    /**
     * Creates a new NTT context.
     *
     * # Arguments
     * - `n` — polynomial size, must be a power of 2 ≥ 2
     * - `q` — prime < 2^28, must satisfy q ≡ 1 (mod 2N)
     *
     * Returns an error if parameters are invalid.
     */
    static tryNew(n: number, q: number): VaeaNtt32;

    /**
     * Returns the polynomial size N.
     */
    getN(): number;

    /**
     * Returns the prime modulus q.
     */
    getQ(): number;

    /**
     * Forward NTT transform (in-place).
     *
     * `data` must have exactly N elements. All elements must be < q.
     */
    forward(data: Array<number>): void;

    /**
     * Inverse NTT transform (in-place, with N⁻¹ normalization).
     *
     * `data` must have exactly N elements.
     */
    inverse(data: Array<number>): void;

    /**
     * Inverse NTT without N⁻¹ normalization (matches concrete-ntt behavior).
     *
     * `data` must have exactly N elements.
     */
    inverseLazy(data: Array<number>): void;

    /**
     * Negacyclic polynomial multiplication in Z_q[X]/(X^N + 1).
     *
     * Computes `result = a × b mod (X^N + 1)` using NTT.
     * All three buffers must have exactly N elements.
     * `a` and `b` are modified (transformed to NTT domain).
     */
    negacyclicMul(a: Array<number>, b: Array<number>, result: Array<number>): void;

    /**
     * Pointwise multiplication of two NTT-domain polynomials.
     *
     * All three buffers must have exactly N elements.
     * Inputs must already be in NTT domain.
     */
    pointwiseMul(a: Array<number>, b: Array<number>, result: Array<number>): void;
}